app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
#Laravel 5.1 默认路由
Route::get('/', function () {
    return view('welcome');
});
*/

//added some test routes



#对后台开启csrf过滤
Route::when('admin/*', 'csrf', ['post','delete','put']);

/*
|--------------------------------------------------------------------------
| 基础权限 登录注册找回密码等操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'auth'], function () {
	$Authority = 'AuthorityController@';
	# 退出
	Route::get('logout', ['as' => 'logout', 'uses' => $Authority.'getLogout']);
	# 登录
	Route::get('login', ['as' => 'login', 'uses' => $Authority.'getLogin']);
	Route::post('login', $Authority.'postLogin');
});


/*
|--------------------------------------------------------------------------
| 管理员后台 实现文章和用户等管理操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {

# 后台首页
	$Admin = 'AdminController@';
	# 访问后台首页 会 重定向至 后台控制台概要页面 （在控制器方法getIndex中处理）
	Route::get('/', ['as' => 'admin', 'uses' => $Admin.'getIndex']);


# 后台上传图片文件layer
	Route::get('/upload', ['as' => 'admin.upload', 'uses' => $Admin.'getUpload']);
	Route::post('/upload', ['as' => 'admin.upload.store', 'uses' => $Admin.'postUpload']);

#重建缓存（更新内容或者刚安装完本CMS之后，如果数据显示异常，请点击后台导航中“重建缓存”链接）
	Route::get('/cache', ['as' => 'admin.cache', 'uses' => $Admin.'getRebuildCache']);

#--------------------
# 控制台 START
#--------------------

	Route::group(['prefix' => 'console'], function (){
		$resource = 'admin.console';
		$controller = 'Admin\AdminConsoleController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'getIndex']);
	});

#--------------------
# 控制台 END
#--------------------


#--------------------
# 内容管理 START
#--------------------

	# 文章
	Route::resource('article', 'Admin\AdminArticleController');
	
	# 单页
	Route::resource('page', 'Admin\AdminPageController');
	
	#碎片
	Route::resource('fragment', 'Admin\AdminFragmentController');
	
	# 分类
	Route::resource('category','Admin\AdminCategoryController');

	# 标签
	Route::resource ('tag','Admin\AdminTagController');

#--------------------
# 内容管理 END
#--------------------

#--------------------
# 用户管理 START
#--------------------
	#我的账户
	Route::get('/me', ['as'=>'admin.me.index', 'uses'=>'Admin\AdminMeController@getIndex']);
	Route::put('/me', ['as'=>'admin.me.update', 'uses'=>'Admin\AdminMeController@putUpdate']);

	#管理型用户
	Route::group( ['prefix' => 'user'], function () {
		$resource = 'admin.user';
		$controller = 'Admin\AdminUserController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'index'] );  //管理型用户列表
		Route::get( 'create', ['as' => $resource.'.create', 'uses' => $controller.'create'] );  //新增管理型用户
		Route::post( '/', ['as' => $resource.'.store', 'uses' => $controller.'store'] );  //post处理提交数据
		Route::get( '{id}', ['as' => $resource.'.show', 'uses' => $controller.'show'] );  //展示管理型用户个人基础信息
		Route::get('{id}/edit', ['as' => $resource.'.edit', 'uses' => $controller.'edit'] );  //修改管理型用户信息
		Route::put( '{id}', ['as' => $resource.'.update', 'uses' => $controller.'update'] );  //put更新管理型用户信息
	});



	#角色
	Route::resource('role', 'Admin\AdminRoleController');

	#权限
	Route::get('/permission', ['as' => 'admin.permission.index', 'uses' => 'Admin\AdminPermissionController@index']);
#--------------------
# 用户管理 END
#--------------------

#--------------------
# 业务管理 START
#--------------------

	#首页
	Route::get('/business', ['as' => 'admin.business.index', 'uses' => 'Admin\AdminBusinessController@getIndex']);
	
	#流程
	Route::get('/flow', ['as' => 'admin.flow','uses' => 'Admin\AdminBusinessController@getFlow']);


#--------------------
# 业务管理 END
#--------------------

#--------------------
# 系统管理 START
#--------------------

	#动态设置 [包含动态设置分组]

	Route::resource('setting', 'Admin\AdminSettingController');  //动态设置
	Route::resource('setting_type','Admin\AdminSettingTypeController');  //动态设置分组

	#静态系统配置
	Route::get('/system_option', ['as'=>'admin.system_option.index', 'uses'=>'Admin\AdminSystemOptionController@getIndex']);
	Route::put('/system_option', ['as'=>'admin.system_option.update', 'uses'=>'Admin\AdminSystemOptionController@putUpdate']);

	#系统日志
	Route::resource('system_log', 'Admin\AdminSystemLogController');  //系统日志
#--------------------
# 系统管理 END
#--------------------
});

/*
|--------------------------------------------------------------------------
| 网站前台博客
|--------------------------------------------------------------------------
*/

Route::group(array(), function () {
	$Blog = 'BlogController@';

	# 前台博客首页
	Route::get('/', ['as' => 'home', 'uses' => $Blog.'getIndex']);

	# 归档页面
	Route::get('archive', ['as' => 'archive', 'uses' => $Blog.'getArchive']);

	# 展示单页 如果单页无slug，则{page}取其id
	Route::get('{page}.html', ['as' => 'page.show', 'uses' => $Blog.'getPageShow']);

	# 展示分类 如果分类无slug，则{category}取其id
	Route::get('{category}', ['as' => 'article.category', 'uses' => $Blog.'getCategoryArticles']);

	# 展示文章 如果分类无slug或者其slug为数字，则将{category}拼接成'cat_{id}'形式；如果文章无slug，则{article}取其id
	Route::get('{category}/{article}.html', ['as' => 'article.show', 'uses' => $Blog.'getArticleShow']);
});

app/Http/Controllers/Admin/BackController.php
<?php

namespace Douyasi\Http\Controllers\Admin;

use Douyasi\Http\Controllers\CommonController as CommonController;

/**
 * 后台共用控制器
 * BackController
 */
class BackController extends CommonController
{
    
    public function __construct()
    {
    }
}

resources/views/back/fragment/create.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            内容管理
            <small>碎片</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li><a href="{{ route('admin.page.index') }}">内容管理 - 单页</a></li>
            <li class="active">新增碎片</li>
          </ol>
@stop

@section('content')

          @if(Session::has('fail'))
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4>  <i class="icon icon fa fa-warning"></i> 提示！</h4>
              {{ Session::get('fail') }}
            </div>
          @endif

          @if($errors->any())
            <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4><i class="icon fa fa-ban"></i> 警告！</h4>
                  <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                  </ul>
            </div>
          @endif

              <h2 class="page-header">新增碎片</h2>
              <form method="post" action="{{ route('admin.fragment.store') }}" accept-charset="utf-8">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="nav-tabs-custom">
                  
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">主要内容</a></li>
                  </ul>

                  <div class="tab-content">
                    
                    <div class="tab-pane active" id="tab_1">
                      <div class="form-group">
                        <label>标题 <small class="text-red">*</small></label>
                        <input type="text" class="form-control" name="title" autocomplete="off" value="{{ Input::old('title') }}" placeholder="标题">
                      </div>
                      <div class="form-group">
                        <label>slug（碎片标识符） <small class="text-red">*</small></label>
                        <div class="input-group mono url_slug">
                          <input type="text" id="slug" name="slug" autocomplete="off" value="{{ Input::old('slug') }}" placeholder="slug" class="slug" maxlength="20" pattern="[A-z0-9_-]+">
                        </div>
                      </div>
                      <div class="form-group">
                        <label>缩略图  <a href="javascript:void(0);" class="uploadPic" data-id="thumb"><i class="fa fa-fw fa-picture-o" title="上传"></i></a>  <a href="javascript:void(0);" class="previewPic" data-id="thumb"><i class="fa fa-fw fa-eye" title="预览小图"></i></a></label>
                        <input type="text" class="form-control" id="thumb" name="thumb" value="{{ Input::old('thumb') }}" placeholder="缩略图地址：如{{ url('') }}/assets/img/yas_logo.png">
                      </div>
                      <div class="form-group">
                        <label>正文 <small class="text-red">*</small></label>
                        <textarea class="form-control" id="ckeditor" name="content">{{ Input::old('content') }}</textarea>
                        @include('scripts.endSimpleCKEditor'){{-- 使用简版CKEditor --}}
                      </div>
                    </div><!-- /.tab-pane -->

                    <button type="submit" class="btn btn-primary">新增碎片</button>

                  </div><!-- /.tab-content -->
                  
              </div>
              </form>
          <div id="layerPreviewPic" class="fn-hide">
            
          </div>

@stop

@section('extraPlugin')

  <!--引入Layer组件-->
  <script src="{{ asset('plugins/layer/layer.min.js') }}"></script>

@stop


@section('filledScript')
        <!--缩略名自适应宽度 来自typecho-->
        var slug = $('#slug');

        if (slug.length > 0) {
          var sw = slug.width();
          if (slug.val().length > 0) {
            slug.css('width', 'auto').attr('size', slug.val().length);
          }
          slug.bind('input propertychange', function () {
            var t = $(this), l = t.val().length;
            if (l > 0) {
              t.css('width', 'auto').attr('size', l);
            } else {
              t.css('width', sw).removeAttr('size');
            }
          }).width();
        }

        @include('scripts.endSinglePic') {{-- 引入单个图片上传与预览JS，依赖于Layer --}}
@stop

resources/views/back/fragment/edit.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            内容管理
            <small>碎片</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li><a href="{{ route('admin.fragment.index') }}">内容管理 - 碎片</a></li>
            <li class="active">修改碎片</li>
          </ol>
@stop

@section('content')

          @if(Session::has('fail'))
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4>  <i class="icon icon fa fa-warning"></i> 提示！</h4>
              {{ Session::get('fail') }}
            </div>
          @endif

          @if($errors->any())
            <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4><i class="icon fa fa-ban"></i> 警告！</h4>
                  <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                  </ul>
            </div>
          @endif

              <h2 class="page-header">修改碎片</h2>
              <form method="post" action="{{ route('admin.fragment.update', $data->id) }}" accept-charset="utf-8">
              <input name="_method" type="hidden" value="put">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="nav-tabs-custom">
                  
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">主要内容</a></li>
                  </ul>

                  <div class="tab-content">
                    {{-- 这里需兼顾初次传入，以及提交过未通过的闪存数据 --}}
                    <div class="tab-pane active" id="tab_1">
                      <div class="form-group">
                        <label>标题 <small class="text-red">*</small></label>
                        <input type="text" class="form-control" name="title" autocomplete="off" value="{{ Input::old('title', isset($data) ? $data->title : null) }}" placeholder="标题">
                      </div>
                      <div class="form-group">
                        <label>slug（碎片标识符） <small class="text-red">*</small></label>
                        <div class="input-group mono url_slug">
                          <input type="text" id="slug" name="slug" autocomplete="off" value="{{ Input::old('slug', isset($data) ? $data->slug : null) }}" placeholder="slug" class="slug" maxlength="20" pattern="[A-z0-9_-]+">
                        </div>
                      </div>
                      <div class="form-group">
                        <label>缩略图  <a href="javascript:void(0);" class="uploadPic" data-id="thumb"><i class="fa fa-fw fa-picture-o" title="上传"></i></a>  <a href="javascript:void(0);" class="previewPic" data-id="thumb"><i class="fa fa-fw fa-eye" title="预览小图"></i></a></label>
                        <input type="text" class="form-control" id="thumb" name="thumb" value="{{ Input::old('thumb', isset($data) ? $data->thumb : null) }}" placeholder="缩略图地址：如{{ url('') }}/assets/img/yas_logo.png">
                      </div>
                      <div class="form-group">
                        <label>正文 <small class="text-red">*</small></label>
                        <textarea class="form-control" id="ckeditor" name="content">{{ Input::old('content', isset($data) ? $data->content : null) }}</textarea>
                        @include('scripts.endCKEditor'){{-- 引入CKEditor编辑器相关JS依赖 --}}
                      </div>
                    </div><!-- /.tab-pane -->

                    <button type="submit" class="btn btn-primary">修改碎片</button>

                  </div><!-- /.tab-content -->
                  
              </div>
              </form>
          <div id="layerPreviewPic" class="fn-hide">
            
          </div>

@stop

@section('extraPlugin')

  <!--引入Layer组件-->
  <script src="{{ asset('plugins/layer/layer.min.js') }}"></script>

@stop


@section('filledScript')
        <!--缩略名自适应宽度 来自typecho-->
        var slug = $('#slug');

        if (slug.length > 0) {
          var sw = slug.width();
          if (slug.val().length > 0) {
            slug.css('width', 'auto').attr('size', slug.val().length);
          }
          slug.bind('input propertychange', function () {
            var t = $(this), l = t.val().length;
            if (l > 0) {
              t.css('width', 'auto').attr('size', l);
            } else {
              t.css('width', sw).removeAttr('size');
            }
          }).width();
        }

        @include('scripts.endSinglePic') {{-- 引入单个图片上传与预览JS，依赖于Layer --}}
@stop

resources/views/back/fragment/index.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            内容管理
            <small>碎片</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">内容管理 - 碎片</li>
          </ol>
@stop

@section('content')

              @if(Session::has('message'))
                <div class="alert alert-success alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4>  <i class="icon fa fa-check"></i> 提示！</h4>
                  {{ Session::get('message') }}
                </div>
              @endif

              <a href="{{ route('admin.fragment.create') }}" class="btn btn-primary margin-bottom">新增碎片</a>

              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">碎片列表</h3>
                  <div class="box-tools">
                    <form action="{{ route('admin.fragment.index') }}" method="get">
                      <div class="input-group">
                        <input type="text" class="form-control input-sm pull-right" name="s_title" value="{{ Input::get('s_title') }}" style="width: 150px;" placeholder="搜索碎片标题">
                        <input type="text" class="form-control input-sm pull-right" name="s_slug" value="{{ Input::get('s_slug') }}" style="width: 150px;" placeholder="搜索碎片slug">
                        <div class="input-group-btn">
                          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <div class="box-tips clearfix">
                    <p>
                      <b>碎片</b>一般为简短内容片段，可在模版中直接调用，blade模版中调用方法为 <code>
                        &#123;&#123; fragment($slug,$ret='') &#125;&#125;</code>  或  <code>&#123;!! fragment($slug,$ret='') !!&#125;</code>，具体查阅说明文档。
                    </p>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive">
                  <div class="tablebox-controls">
                    <!-- Check all button -->
                    <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o" title="全选/反全选"></i></button>
                    <button class="btn btn-default btn-sm"><i class="fa fa-trash-o" title="删除"></i></button>
                    <button class="btn btn-default btn-sm"><i class="fa fa-refresh" title="刷新"></i></button>
                  </div>
                  <table class="table table-hover table-bordered">
                    <tbody>
                      <!--tr-th start-->
                      <tr>
                        <th>选择</th>
                        <th>操作</th>
                        <th>标题</th>
                        <th>slug（碎片标识符）</th>
                        <th>创建时间</th>
                        <th>最后修改时间</th>
                      </tr>
                      <!--tr-th end-->

                      @foreach ($fragments as $fra)
                      <tr>
                        <td class="table-operation"><input type="checkbox" value="{{ $fra->id }}" name="checkbox[]"></td>
                        <td>
                            <a href="{{ route('admin.fragment.index') }}/{{ $fra->id }}/edit"><i class="fa fa-fw fa-pencil" title="修改"></i></a>  
                            <a href="javascript:void(0);"><i class="fa fa-fw fa-link" title="预览"></i></a>  
                            <a href="javascript:void(0);"><i class="fa fa-fw fa-minus-circle delete_item" title="删除" data-id="{{ $fra->id }}"></i></a>
                        </td>
                        <td class="text-muted">{{ str_limit($fra->title,36) }}</td>
                        <td class="text-green">
                          @if(empty($fra->slug))
                          {{ $fra->id }}
                          @else
                          {{ $fra->slug }}
                          @endif
                        </td>
                        <td>{{ $fra->created_at }}</td>
                        <td>{{ $fra->updated_at }}</td>
                      </tr>
                      @endforeach

                    </tbody>
                  </table>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                  {!! $fragments->render() !!}
                </div>

                <!--隐藏型删除表单-->
                <form method="post" action="{{ route('admin.fragment.index') }}" accept-charset="utf-8" id="hidden-delete-form">
                <input name="_method" type="hidden" value="delete">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </form>

              </div>
@stop

@section('extraPlugin')
<!--引入iCheck组件-->
<script src="{{ asset('plugins/iCheck/icheck.min.js') }}" type="text/javascript"></script>
@stop

@section('filledScript')
        <!--启用iCheck响应checkbox与radio表单控件-->
        //Enable iCheck plugin for checkboxes
        //iCheck for checkbox and radio inputs
        $('.table-operation input[type="checkbox"]').iCheck({
          checkboxClass: 'icheckbox_flat-blue',
          radioClass: 'iradio_flat-blue'
        });

        //Enable check and uncheck all functionality
        $(".checkbox-toggle").click(function () {
          var clicks = $(this).data('clicks');
          if (clicks) {
            //Uncheck all checkboxes
            $(".table-operation input[type='checkbox']").iCheck("uncheck");
            $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
          } else {
            //Check all checkboxes
            $(".table-operation input[type='checkbox']").iCheck("check");
            $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
          }
          $(this).data("clicks", !clicks);
        });

        <!--jQuery 提交表单，实现DELETE删除资源-->
        //jQuery submit form
        $('.delete_item').click(function(){
            var action = '{{ route('admin.fragment.index') }}';
            var id = $(this).data('id');
            var new_action = action + '/' + id;
            $('#hidden-delete-form').attr('action', new_action);
            $('#hidden-delete-form').submit();
        });
@stop