app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
#Laravel 5.1 默认路由
Route::get('/', function () {
    return view('welcome');
});
*/

//added some test routes



#对后台开启csrf过滤
Route::when('admin/*', 'csrf', ['post','delete','put']);

/*
|--------------------------------------------------------------------------
| 基础权限 登录注册找回密码等操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'auth'], function () {
	$Authority = 'AuthorityController@';
	# 退出
	Route::get('logout', ['as' => 'logout', 'uses' => $Authority.'getLogout']);
	# 登录
	Route::get('login', ['as' => 'login', 'uses' => $Authority.'getLogin']);
	Route::post('login', $Authority.'postLogin');
});


/*
|--------------------------------------------------------------------------
| 管理员后台 实现文章和用户等管理操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {

# 后台首页
	$Admin = 'AdminController@';
	# 访问后台首页 会 重定向至 后台控制台概要页面 （在控制器方法getIndex中处理）
	Route::get('/', ['as' => 'admin', 'uses' => $Admin.'getIndex']);


# 后台上传图片文件layer
	Route::get('/upload', ['as' => 'admin.upload', 'uses' => $Admin.'getUpload']);
	Route::post('/upload', ['as' => 'admin.upload.store', 'uses' => $Admin.'postUpload']);

#重建缓存（更新内容或者刚安装完本CMS之后，如果数据显示异常，请点击后台导航中“重建缓存”链接）
	Route::get('/cache', ['as' => 'admin.cache', 'uses' => $Admin.'getRebuildCache']);

#--------------------
# 控制台 START
#--------------------

	Route::group(['prefix' => 'console'], function (){
		$resource = 'admin.console';
		$controller = 'Admin\AdminConsoleController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'getIndex']);
	});

#--------------------
# 控制台 END
#--------------------


#--------------------
# 内容管理 START
#--------------------

	# 文章
	Route::resource('article', 'Admin\AdminArticleController');
	
	# 单页
	Route::resource('page', 'Admin\AdminPageController');
	
	#碎片
	Route::resource('fragment', 'Admin\AdminFragmentController');
	
	# 分类
	Route::resource('category','Admin\AdminCategoryController');

	# 标签
	Route::resource ('tag','Admin\AdminTagController');

#--------------------
# 内容管理 END
#--------------------

#--------------------
# 用户管理 START
#--------------------
	#我的账户
	Route::get('/me', ['as'=>'admin.me.index', 'uses'=>'Admin\AdminMeController@getIndex']);
	Route::put('/me', ['as'=>'admin.me.update', 'uses'=>'Admin\AdminMeController@putUpdate']);

	#管理型用户
	Route::group( ['prefix' => 'user'], function () {
		$resource = 'admin.user';
		$controller = 'Admin\AdminUserController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'index'] );  //管理型用户列表
		Route::get( 'create', ['as' => $resource.'.create', 'uses' => $controller.'create'] );  //新增管理型用户
		Route::post( '/', ['as' => $resource.'.store', 'uses' => $controller.'store'] );  //post处理提交数据
		Route::get( '{id}', ['as' => $resource.'.show', 'uses' => $controller.'show'] );  //展示管理型用户个人基础信息
		Route::get('{id}/edit', ['as' => $resource.'.edit', 'uses' => $controller.'edit'] );  //修改管理型用户信息
		Route::put( '{id}', ['as' => $resource.'.update', 'uses' => $controller.'update'] );  //put更新管理型用户信息
	});



	#角色
	Route::resource('role', 'Admin\AdminRoleController');

	#权限
	Route::get('/permission', ['as' => 'admin.permission.index', 'uses' => 'Admin\AdminPermissionController@index']);
#--------------------
# 用户管理 END
#--------------------

#--------------------
# 业务管理 START
#--------------------

	#首页
	Route::get('/business', ['as' => 'admin.business.index', 'uses' => 'Admin\AdminBusinessController@getIndex']);
	
	#流程
	Route::get('/flow', ['as' => 'admin.flow','uses' => 'Admin\AdminBusinessController@getFlow']);


#--------------------
# 业务管理 END
#--------------------

#--------------------
# 系统管理 START
#--------------------

	#动态设置 [包含动态设置分组]

	Route::resource('setting', 'Admin\AdminSettingController');  //动态设置
	Route::resource('setting_type','Admin\AdminSettingTypeController');  //动态设置分组

	#静态系统配置
	Route::get('/system_option', ['as'=>'admin.system_option.index', 'uses'=>'Admin\AdminSystemOptionController@getIndex']);
	Route::put('/system_option', ['as'=>'admin.system_option.update', 'uses'=>'Admin\AdminSystemOptionController@putUpdate']);

	#系统日志
	Route::resource('system_log', 'Admin\AdminSystemLogController');  //系统日志
#--------------------
# 系统管理 END
#--------------------
});

/*
|--------------------------------------------------------------------------
| 网站前台博客
|--------------------------------------------------------------------------
*/

Route::group(array(), function () {
	$Blog = 'BlogController@';

	# 前台博客首页
	Route::get('/', ['as' => 'home', 'uses' => $Blog.'getIndex']);

	# 归档页面
	Route::get('archive', ['as' => 'archive', 'uses' => $Blog.'getArchive']);

	# 展示单页 如果单页无slug，则{page}取其id
	Route::get('{page}.html', ['as' => 'page.show', 'uses' => $Blog.'getPageShow']);

	# 展示分类 如果分类无slug，则{category}取其id
	Route::get('{category}', ['as' => 'article.category', 'uses' => $Blog.'getCategoryArticles']);

	# 展示文章 如果分类无slug或者其slug为数字，则将{category}拼接成'cat_{id}'形式；如果文章无slug，则{article}取其id
	Route::get('{category}/{article}.html', ['as' => 'article.show', 'uses' => $Blog.'getArticleShow']);
});

app/Models/Setting.php
<?php

namespace Douyasi\Models;

use Eloquent;

/**
 * 动态设置模型
 *
 * @author raoyc <raoyc2009@gmail.com>
 */
class Setting extends Eloquent
{
    
    protected $table = 'settings';
    
    public $timestamps = false;  //关闭自动更新时间戳

    /**
     * 动态设置分组
     * 模型对象关系：动态设置对应的分组
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function setting_type()
    {
        return $this->belongsTo('Douyasi\Models\SettingType');
    }
}

app/Models/SettingType.php
<?php

namespace Douyasi\Models;

use Eloquent;

/**
 * 动态设置类型模型
 *
 * @author raoyc <raoyc2009@gmail.com>
 */
class SettingType extends Eloquent
{
    
    protected $table = 'setting_type';
    
    public $timestamps = false;  //关闭自动更新时间戳

     /**
     * 动态设置
     * 模型对象关系：(动态设置)分组对应的动态设置（一个分组可以有多个设置项）
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function setting()
    {
        return $this->hasMany('Douyasi\Models\Setting', 'type_id', 'id');
    }
}

app/Http/Controllers/Admin/BackController.php
<?php

namespace Douyasi\Http\Controllers\Admin;

use Douyasi\Http\Controllers\CommonController as CommonController;

/**
 * 后台共用控制器
 * BackController
 */
class BackController extends CommonController
{
    
    public function __construct()
    {
    }
}

resources/views/back/setting/create.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            系统管理
            <small>动态设置</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li><a href="{{ route('admin.page.index') }}">系统管理 - 动态设置</a></li>
            <li class="active">新增动态设置</li>
          </ol>
@stop

@section('content')

          @if(Session::has('fail'))
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4>  <i class="icon icon fa fa-warning"></i> 提示！</h4>
              {{ Session::get('fail') }}
            </div>
          @endif

          @if($errors->any())
            <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4><i class="icon fa fa-ban"></i> 警告！</h4>
                  <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                  </ul>
            </div>
          @endif

              <h2 class="page-header">新增动态设置</h2>
              <form method="post" action="{{ route('admin.setting.store') }}" accept-charset="utf-8">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="nav-tabs-custom">
                  
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">主要内容</a></li>
                  </ul>

                  <div class="tab-content">
                    
                    <div class="tab-pane active" id="tab_1">
                      <div class="form-group">
                        <label>动态设置名 <small class="text-red">*</small> <span class="text-green small">只能数字、字母、下划线与横杠（0-9a-zA-Z_-）组合</span></label>
                        <input type="text" class="form-control" name="name" autocomplete="off" value="{{ Input::old('name') }}" placeholder="动态设置名">
                      </div>
                      <div class="form-group">
                        <label>动态设置值 <small class="text-red">*</small></label>
                        <input type="text" class="form-control" name="value" value="{{ Input::old('value') }}" placeholder="动态设置值">
                      </div>
                      <div class="form-group">
                        <label>动态设置分组 <small class="text-red">*</small></label>
                        <div class="input-group">
                          <select data-placeholder="选择动态设置分组" class="chosen-select" style="min-width:200px;" name="type_id">
                          @foreach ($types as $type)
                            <option value="{{ $type->id }}" {{ ($type->id == Input::get('s_tid','1')) ? 'selected':'' }}>{{ $type->value }}</option>
                          @endforeach
                          </select>
                        </div>
                      </div>
                    </div><!-- /.tab-pane -->

                    <button type="submit" class="btn btn-primary">新增动态设置</button>

                  </div><!-- /.tab-content -->
                  
              </div>
              </form>

@stop


@section('extraPlugin')

  <!--引入Chosen组件-->
  @include('scripts.endChosen')

@stop

resources/views/back/setting/edit.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            系统管理
            <small>动态设置</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li><a href="{{ route('admin.page.index') }}">系统管理 - 动态设置</a></li>
            <li class="active">修改动态设置</li>
          </ol>
@stop

@section('content')

          @if(Session::has('fail'))
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4>  <i class="icon icon fa fa-warning"></i> 提示！</h4>
              {{ Session::get('fail') }}
            </div>
          @endif

          @if($errors->any())
            <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4><i class="icon fa fa-ban"></i> 警告！</h4>
                  <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                  </ul>
            </div>
          @endif

              <h2 class="page-header">修改动态设置</h2>
              <form method="post" action="{{ route('admin.setting.update', $data->id) }}" accept-charset="utf-8">
              <input name="_method" type="hidden" value="put">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="nav-tabs-custom">
                  
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">主要内容</a></li>
                  </ul>

                  <div class="tab-content">
                    
                    <div class="tab-pane active" id="tab_1">
                      <div class="form-group">
                        <label>动态设置名 <small class="text-red">*</small> <span class="text-green small">只能全小写的英文字母与下划线（a-z_）组合</span></label>
                        <input type="text" class="form-control" name="name" autocomplete="off" value="{{ Input::old('name', isset($data) ? $data->name : null) }}" placeholder="动态设置名">
                      </div>
                      <div class="form-group">
                        <label>动态设置值 <small class="text-red">*</small></label>
                        <input type="text" class="form-control" name="value" value="{{ Input::old('value', isset($data) ? $data->value : null) }}" placeholder="动态设置值">
                      </div>
                      <div class="form-group">
                        <label>动态设置分组 <small class="text-red">*</small></label>
                        <div class="input-group">
                          <select data-placeholder="选择动态设置分组" class="chosen-select" style="min-width:200px;" name="type_id">
                            @foreach ($types as $type)
                              <option value="{{ $type->id }}" {{ ($data->type_id === $type->id) ? 'selected':'' }}>{{ $type->value }}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label>状态 <small class="text-red">*</small></label>
                        <div class="input-group">
                          <input type="radio" name="status" value="0" {{ ($data->status === 0) ? 'checked' : '' }}>
                          <label class="choice" for="radiogroup">禁用</label>
                          <input type="radio" name="status" value="1" {{ ($data->status === 1) ? 'checked' : '' }}>
                          <label class="choice" for="radiogroup">启用</label>
                        </div>
                      </div>
                      <div class="form-group">
                        <label>排序 <small class="text-red">*</small> <span class="text-green small">只能数字，数字越大排序越靠前</span></label>
                        <input type="text" class="form-control" name="sort" value="{{ Input::old('sort', isset($data) ? $data->sort : null) }}" maxlength="6" placeholder="排序">
                      </div>
                    </div><!-- /.tab-pane -->

                    <button type="submit" class="btn btn-primary">修改动态设置</button>

                  </div><!-- /.tab-content -->
                  
              </div>
              </form>

@stop


@section('extraPlugin')
  <!--引入iCheck组件-->
  <script src="{{ asset('plugins/iCheck/icheck.min.js') }}" type="text/javascript"></script>
  <!--引入Chosen组件-->
  @include('scripts.endChosen')
@stop


@section('filledScript')
        <!--启用iCheck响应checkbox与radio表单控件-->
        $('input[type="radio"]').iCheck({
          radioClass: 'iradio_flat-blue',
          increaseArea: '20%' // optional
        });
@stop

resources/views/back/setting/index.blade.php
@extends('layout._back')

@section('content-header')
@parent
          <h1>
            系统管理
            <small>动态设置</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">系统管理 - 动态设置</li>
          </ol>
@stop

@section('content')

              @if(Session::has('message'))
                <div class="alert alert-success alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h4>  <i class="icon fa fa-check"></i> 提示！</h4>
                  {{ Session::get('message') }}
                </div>
              @endif

              <a href="{{ route('admin.setting.create', array('s_tid' => Request::segment(3))) }}" class="btn btn-primary margin-bottom">新增动态设置</a>

              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">动态设置列表</h3>
                  <div class="box-tools">
                    <form action="{{ route('admin.setting.index') }}" method="get">
                      <div class="input-group">
                        <input type="text" class="form-control input-sm pull-right" name="s_value" value="{{ Input::get('s_value') }}" style="width: 150px;" placeholder="搜索值">
                        <input type="text" class="form-control input-sm pull-right" name="s_name" value="{{ Input::get('s_name') }}" style="width: 150px;" placeholder="搜索名">
                        <div class="input-group-btn">
                          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive">
                  <table class="table table-hover table-bordered">
                    <tbody>
                      <!--tr-th start-->
                      <tr>
                        <th>选择</th>
                        <th>操作</th>
                        <th>分组名/值</th>
                        <th>名</th>
                        <th>值</th>
                      </tr>
                      <!--tr-th end-->

                      @foreach ($settings as $set)
                      <tr>

                        <td class="table-operation"><input type="checkbox" value="{{ $set->id }}" name="checkbox[]"></td>
                        <td>
                            <a href="{{ route('admin.setting.index') }}/{{ $set->id }}/edit"><i class="fa fa-fw fa-pencil" title="修改"></i></a>  
                            <a href="javascript:void(0);"><i class="fa fa-fw fa-link" title="预览"></i></a>  
                            <a href="javascript:void(0);"><i class="fa fa-fw fa-minus-circle delete_item" title="删除" data-id="{{ $set->id }}"></i></a>
                        </td>
                        <td>
                          <a href="{{ route('admin.setting_type.index') }}/{{ $set->tid }}">{{ $set->tname }}/{{ $set->tvalue }}</a>
                        </td>
                        <td class="text-red">{{ $set->name }}</td>
                        <td class="text-green">{{ $set->value }}</td>
                      </tr>
                      @endforeach

                    </tbody>
                  </table>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                  {!! $settings->render() !!}
                </div>

                <!--隐藏型删除表单-->
                <form method="post" action="{{ route('admin.setting.index') }}" accept-charset="utf-8" id="hidden-delete-form">
                <input name="_method" type="hidden" value="delete">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </form>

              </div>
@stop


@section('extraPlugin')
<!--引入iCheck组件-->
<script src="{{ asset('plugins/iCheck/icheck.min.js') }}" type="text/javascript"></script>
@stop

@section('filledScript')
        <!--启用iCheck响应checkbox与radio表单控件-->
        //Enable iCheck plugin for checkboxes
        //iCheck for checkbox and radio inputs
        $('.table-operation input[type="checkbox"]').iCheck({
          checkboxClass: 'icheckbox_flat-blue',
          radioClass: 'iradio_flat-blue'
        });

        //Enable check and uncheck all functionality
        $(".checkbox-toggle").click(function () {
          var clicks = $(this).data('clicks');
          if (clicks) {
            //Uncheck all checkboxes
            $(".table-operation input[type='checkbox']").iCheck("uncheck");
            $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
          } else {
            //Check all checkboxes
            $(".table-operation input[type='checkbox']").iCheck("check");
            $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
          }
          $(this).data("clicks", !clicks);
        });

        <!--jQuery 提交表单，实现DELETE删除资源-->
        //jQuery submit form
        $('.delete_item').click(function(){
            var action = '{{ route('admin.setting.index') }}';
            var id = $(this).data('id');
            var new_action = action + '/' + id;
            $('#hidden-delete-form').attr('action', new_action);
            $('#hidden-delete-form').submit();
        });
@stop