app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
#Laravel 5.1 默认路由
Route::get('/', function () {
    return view('welcome');
});
*/

//added some test routes



#对后台开启csrf过滤
Route::when('admin/*', 'csrf', ['post','delete','put']);

/*
|--------------------------------------------------------------------------
| 基础权限 登录注册找回密码等操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'auth'], function () {
	$Authority = 'AuthorityController@';
	# 退出
	Route::get('logout', ['as' => 'logout', 'uses' => $Authority.'getLogout']);
	# 登录
	Route::get('login', ['as' => 'login', 'uses' => $Authority.'getLogin']);
	Route::post('login', $Authority.'postLogin');
});


/*
|--------------------------------------------------------------------------
| 管理员后台 实现文章和用户等管理操作
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {

# 后台首页
	$Admin = 'AdminController@';
	# 访问后台首页 会 重定向至 后台控制台概要页面 （在控制器方法getIndex中处理）
	Route::get('/', ['as' => 'admin', 'uses' => $Admin.'getIndex']);


# 后台上传图片文件layer
	Route::get('/upload', ['as' => 'admin.upload', 'uses' => $Admin.'getUpload']);
	Route::post('/upload', ['as' => 'admin.upload.store', 'uses' => $Admin.'postUpload']);

#重建缓存（更新内容或者刚安装完本CMS之后，如果数据显示异常，请点击后台导航中“重建缓存”链接）
	Route::get('/cache', ['as' => 'admin.cache', 'uses' => $Admin.'getRebuildCache']);

#--------------------
# 控制台 START
#--------------------

	Route::group(['prefix' => 'console'], function (){
		$resource = 'admin.console';
		$controller = 'Admin\AdminConsoleController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'getIndex']);
	});

#--------------------
# 控制台 END
#--------------------


#--------------------
# 内容管理 START
#--------------------

	# 文章
	Route::resource('article', 'Admin\AdminArticleController');
	
	# 单页
	Route::resource('page', 'Admin\AdminPageController');
	
	#碎片
	Route::resource('fragment', 'Admin\AdminFragmentController');
	
	# 分类
	Route::resource('category','Admin\AdminCategoryController');

	# 标签
	Route::resource ('tag','Admin\AdminTagController');

#--------------------
# 内容管理 END
#--------------------

#--------------------
# 用户管理 START
#--------------------
	#我的账户
	Route::get('/me', ['as'=>'admin.me.index', 'uses'=>'Admin\AdminMeController@getIndex']);
	Route::put('/me', ['as'=>'admin.me.update', 'uses'=>'Admin\AdminMeController@putUpdate']);

	#管理型用户
	Route::group( ['prefix' => 'user'], function () {
		$resource = 'admin.user';
		$controller = 'Admin\AdminUserController@';
		Route::get( '/', ['as' => $resource.'.index', 'uses' => $controller.'index'] );  //管理型用户列表
		Route::get( 'create', ['as' => $resource.'.create', 'uses' => $controller.'create'] );  //新增管理型用户
		Route::post( '/', ['as' => $resource.'.store', 'uses' => $controller.'store'] );  //post处理提交数据
		Route::get( '{id}', ['as' => $resource.'.show', 'uses' => $controller.'show'] );  //展示管理型用户个人基础信息
		Route::get('{id}/edit', ['as' => $resource.'.edit', 'uses' => $controller.'edit'] );  //修改管理型用户信息
		Route::put( '{id}', ['as' => $resource.'.update', 'uses' => $controller.'update'] );  //put更新管理型用户信息
	});



	#角色
	Route::resource('role', 'Admin\AdminRoleController');

	#权限
	Route::get('/permission', ['as' => 'admin.permission.index', 'uses' => 'Admin\AdminPermissionController@index']);
#--------------------
# 用户管理 END
#--------------------

#--------------------
# 业务管理 START
#--------------------

	#首页
	Route::get('/business', ['as' => 'admin.business.index', 'uses' => 'Admin\AdminBusinessController@getIndex']);
	
	#流程
	Route::get('/flow', ['as' => 'admin.flow','uses' => 'Admin\AdminBusinessController@getFlow']);


#--------------------
# 业务管理 END
#--------------------

#--------------------
# 系统管理 START
#--------------------

	#动态设置 [包含动态设置分组]

	Route::resource('setting', 'Admin\AdminSettingController');  //动态设置
	Route::resource('setting_type','Admin\AdminSettingTypeController');  //动态设置分组

	#静态系统配置
	Route::get('/system_option', ['as'=>'admin.system_option.index', 'uses'=>'Admin\AdminSystemOptionController@getIndex']);
	Route::put('/system_option', ['as'=>'admin.system_option.update', 'uses'=>'Admin\AdminSystemOptionController@putUpdate']);

	#系统日志
	Route::resource('system_log', 'Admin\AdminSystemLogController');  //系统日志
#--------------------
# 系统管理 END
#--------------------
});

/*
|--------------------------------------------------------------------------
| 网站前台博客
|--------------------------------------------------------------------------
*/

Route::group(array(), function () {
	$Blog = 'BlogController@';

	# 前台博客首页
	Route::get('/', ['as' => 'home', 'uses' => $Blog.'getIndex']);

	# 归档页面
	Route::get('archive', ['as' => 'archive', 'uses' => $Blog.'getArchive']);

	# 展示单页 如果单页无slug，则{page}取其id
	Route::get('{page}.html', ['as' => 'page.show', 'uses' => $Blog.'getPageShow']);

	# 展示分类 如果分类无slug，则{category}取其id
	Route::get('{category}', ['as' => 'article.category', 'uses' => $Blog.'getCategoryArticles']);

	# 展示文章 如果分类无slug或者其slug为数字，则将{category}拼接成'cat_{id}'形式；如果文章无slug，则{article}取其id
	Route::get('{category}/{article}.html', ['as' => 'article.show', 'uses' => $Blog.'getArticleShow']);
});

resources/views/widgets/bootstrapCategory.blade.php
            <!-- bootstrap 分类 widget -->
            <ul class="list-group">
            @if(empty($categories))
                <li class="list-group-item">暂无分类</li>
            @else
                @inject('article_service', 'Douyasi\Services\ArticleService') {{-- Blade模版里面服务注入 Laravel 5.1 LTS 新增功能 --}}
                @foreach ($categories as $rCat)
                <li class="list-group-item">
                    <span class="badge">{{ $rCat['count'] }}</span>
                    <a href="{{ $article_service->getCategorySlug($rCat['category']->slug, $rCat['category']->id) }}">{{ $rCat['category']->name }}</a>
                </li>
                @endforeach
            @endif
            </ul>

resources/views/widgets/bootstrapFooter.blade.php
	<!-- 前台bootstrap页脚 -->
	<div class="container" id="footer">
		<div class="row">
			<div class="col-lg-12">
				<ul class="list-unstyled">
				<li class="pull-right"><a href="#top">返回顶部</a></li>
				</ul>
				<p>&copy; {{ date('Y') }} 由  <a href="http://douyasi.com/cmf/yascmf.html">芽丝内容管理框架(YASCMF)</a>  所驱动的博客,  本博客使用 <a href="http://getbootstrap.com/">Bootstrap</a> 构建，更多第三方主题可参阅  <a href="http://bootswatch.com/" target="_blank">Bootswatch</a>  .</p>
			</div>
		</div>
	</div>

resources/views/widgets/bootstrapHeader.blade.php
    
    <!-- 前台bootstrap头部导航 -->
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">{{ Cache::get('website_title','芽丝博客') }}</a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main" aria-expanded="true">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main" aria-expanded="true" style="">
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('home') }}">首页</a>
                    @inject('article_service', 'Douyasi\Services\ArticleService') {{-- Blade模版里面服务注入 Laravel 5.1 LTS 新增功能 --}}
                    @foreach($topPage as $tPage)
                    <li>
                        <a href="{{ $article_service->getPageSlug($tPage->slug, $tPage->id) }}">{{ $tPage->title }}</a>
                    </li>
                    @endforeach
                    <li><a href="{{ route('archive') }}">归档</a>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download" aria-expanded="false">下载 <span class="caret"></span></a>
                        <ul class="dropdown-menu" aria-labelledby="download">
                            <li><a href="https://github.com/douyasi/yascmf">yascmf源码</a></li>
                            <li class="divider"></li>
                            <li><a href="http://www.yas.so/docs">yascmf手册</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <!--<li><a href="#" target="_blank">芽丝官网</a></li>-->
                    @if(Auth::check())
                        <li><a href="{{ route('admin') }}">后台</a></li>
                        <li><a href="{{ route('logout') }}">退出</a></li>
                    @else
                        <li><a href="{{ route('login') }}">登录</a></li>
                    @endif
                </ul>

            </div>
        </div>
    </div>

resources/views/widgets/control-sidebar.blade.php
        {{-- widget.control-sidebar --}}

        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">最近活动</h3>
            <ul class='control-sidebar-menu'>
              <li>
                <a href="javascript:void(0);">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">张三</h4>
                    <p>将在04月24日过他的23岁生日</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">任务进度</h3> 
            <ul class='control-sidebar-menu'>
              <li>
                <a href="javascript:void(0);">
                  <h4 class="control-sidebar-subheading">
                    自定义模版设计
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">常规设置</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  报告面板用法
                  <input type="checkbox" class="pull-right" checked />
                </label>
                <p>
                  关于常规设置选项的一些信息
                </p>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->

        </div>

resources/views/widgets/main-header.blade.php
      {{-- widget.main-header --}}

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>Y</b>AS</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>YAS</b>CMF</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

              <li>
                <a href="{{ route('home') }}">
                  <i class="fa fa-home" title="前台首页"></i>
                  <span class="label label-info">H</span>
                </a>
              </li>

              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">您有 4 条未读信息！</li>
                  <li>
                    <!-- inner menu: contains the messages -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <!-- User Image -->
                            <img src="{{ asset('dist/img/20150417113714.jpg') }}" class="img-circle" alt="User Image"/>
                          </div>
                          <!-- Message title and timestamp -->
                          <h4>
                            支援小组
                            <small><i class="fa fa-clock-o"></i> 5 分钟前</small>
                          </h4>
                          <!-- The message -->
                          <p>为什么不买一个超赞的主题呢？</p>
                        </a>
                      </li><!-- end message -->
                    </ul><!-- /.menu -->
                  </li>
                  <li class="footer"><a href="#">查看所有消息</a></li>
                </ul>
              </li><!-- /.messages-menu -->

              <!-- Notifications Menu -->
              <li class="dropdown notifications-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">您有 10 条通知</li>
                  <li>
                    <!-- Inner Menu: contains the notifications -->
                    <ul class="menu">
                      <li><!-- start notification -->
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 今天有5个新成员加入
                        </a>
                      </li><!-- end notification -->
                    </ul>
                  </li>
                  <li class="footer"><a href="#">查看所有通知</a></li>
                </ul>
              </li>
              <!-- Tasks Menu -->
              <li class="dropdown tasks-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">您有 9 项任务</li>
                  <li>
                    <!-- Inner menu: contains the tasks -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <!-- Task title and progress text -->
                          <h3>
                            设计一些按钮
                            <small class="pull-right">20%</small>
                          </h3>
                          <!-- The progress bar -->
                          <div class="progress xs">
                            <!-- Change the css width attribute to simulate progress -->
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% 完成</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">查看所有任务</a>
                  </li>
                </ul>
              </li>
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <img src="{{ asset('dist/img/20150417113714.jpg') }}" class="user-image" alt="User Image"/>
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs">{{ user('realname') }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <img src="{{ asset('dist/img/20150417113714.jpg') }}" class="img-circle" alt="User Image" />
                    <p>
                      {{ user('realname') }} - {{ user('nickname') }}
                      <small>{{ user('object')->created_at->format('Y-m') }}加入</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-4 text-center">
                      <a href="#">消息</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">任务</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">好友</a>
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{{ route('admin.me.index') }}" class="btn btn-default btn-flat">个人资料</a>
                    </div>
                    <div class="pull-right">
                      <a href="{{ route('logout') }}" class="btn btn-default btn-flat">退出</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-outdent"></i></a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

resources/views/widgets/main-sidebar.blade.php
      {{-- widget.main-sidebar --}}

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{{ asset('dist/img/20150417113714.jpg') }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p>{{ user('realname') }}</p>
              <!-- Status -->
              <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
            </div>
          </div>

          <!-- search form (Optional) -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="搜索..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->

          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">主导航栏</li>
            
            <!--含子节点 且当前状态为active 的一级导航节点-->
            <!--控制台 active treeview-->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i>
                <span>控制面板</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('admin.console.index') }}"><i class="fa fa-circle-o"></i> 概述</a></li>
                <li><a href="{{ route('admin.me.index') }}"><i class="fa fa-circle-o"></i> 个人资料</a></li>
                <li><a href="{{ route('admin.cache') }}"><i class="fa fa-circle-o"></i> 重建缓存</a></li>
              </ul>
            </li>
            <!--//控制台 active treeview-->

            <!--内容管理 treeview-->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i>
                <span>内容管理</span>
                <span class="label label-primary pull-right">4</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('admin.article.index') }}"><i class="fa fa-file-o"></i> 文章</a></li>
                <li><a href="{{ route('admin.page.index') }}"><i class="fa fa-file-o"></i> 单页</a></li>
                <li><a href="{{ route('admin.fragment.index') }}"><i class="fa fa-file-o"></i> 碎片</a></li>
                <li><a href="{{ route('admin.category.index') }}"><i class="fa fa-file-o"></i> 分类</a></li>
              </ul>
            </li>
            <!--//内容管理 treeview-->

            <!--无子节点的一级导航节点-->
            <li><a href="#"><i class='fa fa-book'></i> <span>写作</span></a></li>
            <li><a href="{{ route('admin.tag.index') }}"><i class="fa fa-tags"></i> <span>标签</span></a></li>

            <!--讨论 treeview-->
            <li class="treeview">
              <a href="#">
                <i class='fa fa-comments-o'></i>
                <span>讨论</span>
                <small class="label pull-right bg-green">New</small>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-square-o"></i>节点</a></li>
                <li><a href="#"><i class="fa fa-square-o"></i>话题</a></li>
                <li><a href="#"><i class="fa fa-square-o"></i>审核</a></li>
                <li><a href="#"><i class="fa fa-square-o"></i>举报</a></li>
                <li><a href="#"><i class="fa fa-square-o"></i>论友</a></li>
              </ul>
            </li>
            <!--//讨论 treeview-->

            <!--用户管理 treeview-->
            <li class="treeview">
              <a href="#"><i class='fa fa-user'></i>
                <span>用户管理</span>
                <small class="label pull-right bg-red">5</small>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('admin.user.index') }}"><i class="fa fa-circle-o"></i>管理员</a></li>
                <li><a href="#"><i class="fa fa-circle-o"></i>注册用户</a></li>
                <li><a href="#"><i class="fa fa-circle-o"></i>付费客户</a></li>
                <li><a href="{{ route('admin.role.index') }}"><i class="fa fa-circle-o"></i>角色</a></li>
                <li><a href="{{ route('admin.permission.index') }}"><i class="fa fa-circle-o"></i>权限</a></li>
              </ul>
            </li>
            <!--//用户管理 treeview-->

            <!--业务管理 treeview-->
            <li class="treeview">
              <a href="#"><i class='fa fa-coffee'></i>
                <span>业务管理</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('admin.flow') }}"><i class="fa fa-sitemap"></i>业务流程</a></li>
                <li><a href="#"><i class="fa fa-envelope-o"></i>信息 <span class="label label-success pull-right">4</span></a></li>
                <li><a href="#"><i class="fa fa-bell-o"></i>通知 <span class="label label-warning pull-right">10</span></a></li>
                <li><a href="#"><i class="fa fa-flag-o"></i>任务 <span class="label label-danger pull-right">9</span></a></li>
              </ul>
            </li>
            <!--//业务管理 treeview-->

            <!--系统管理 treeview-->
            <li class="treeview">
              <a href="#"><i class='fa fa-cog'></i>
                <span>系统管理</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('admin.system_option.index') }}"><i class="fa fa-square-o"></i>系统配置</a></li>
                <li><a href="{{ route('admin.setting_type.index') }}"><i class="fa fa-square-o"></i>动态设置分组</a></li>
                <li><a href="{{ route('admin.setting.index') }}"><i class="fa fa-square-o"></i>动态设置</a></li>
                <li><a href="{{ route('admin.system_log.index') }}"><i class="fa fa-square-o"></i>系统日志</a></li>
                <li><a href="#"><i class="fa fa-square-o"></i>邮件日志</a></li>
              </ul>
            </li>
            <!--//系统管理 treeview-->

          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>